# Generated by Django 6.0.1 on 2026-02-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='adress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_outlet.adress'),
        ),
    ]
