# Generated by Django 6.0.2 on 2026-02-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_author_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name_plural': 'Adress Entries'},
        ),
    ]
